INSERT INTO subway_line
VALUES ('1', '1호선');
INSERT INTO subway_line
VALUES ('2', '2호선');
INSERT INTO subway_line
VALUES ('3', '3호선');
INSERT INTO subway_line
VALUES ('4', '4호선');
INSERT INTO subway_line
VALUES ('5', '5호선');
INSERT INTO subway_line
VALUES ('6', '6호선');
INSERT INTO subway_line
VALUES ('7', '7호선');
INSERT INTO subway_line
VALUES ('8', '8호선');
INSERT INTO subway_line
VALUES ('9', '9호선');
INSERT INTO subway_line
VALUES ('D1', '신분당선');
INSERT INTO subway_line
VALUES ('K1', '수인분당선');
INSERT INTO subway_line
VALUES ('K4', '경의중앙선');