spring:
  datasource:
    url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_DB_NAME}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

data:
  seoul:
    authentication_key: ${SEOUL_KEY}

kakao:
  key: ${KAKAO_KEY}

rail_portal:
  disabled_toilet_key: ${RAIL_KEY}

server:
  port: 5000