spring:
  datasource:
    url: jdbc:mysql://${rds.host}:${rds.port}/${rds.db.name}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${rds.username}
    password: ${rds.password}

data:
  seoul:
    authentication_key: ${seoul.key}

kakao:
  key: ${kakao.key}

rail_portal:
  disabled_toilet_key: ${rail.key}

server:
  port: 5000