name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RDS_HOST=${{ secrets.RDS_HOST }}
      RDS_PORT=${{ secrets.RDS_PORT }}
      RDS_DB_NAME=${{ secrets.RDS_DB_NAME }}
      RDS_USERNAME=${{ secrets.RDS_USERNAME }}
      RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}
      SEOUL_KEY=${{ secrets.SEOUL_KEY }}
      KAKAO_KEY=${{ secrets.KAKAO_KEY }}
      RAIL_KEY=${{ secrets.RAIL_KEY }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -Dspring.profiles.active=prod